# Generated by Django 5.0 on 2023-12-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonToSQLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade_code', models.CharField(max_length=20)),
                ('high', models.DecimalField(decimal_places=3, max_digits=20)),
                ('low', models.DecimalField(decimal_places=3, max_digits=20)),
                ('open', models.DecimalField(decimal_places=3, max_digits=20)),
                ('close', models.DecimalField(decimal_places=3, max_digits=20)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
