# Generated by Django 5.0 on 2023-12-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonmodel',
            name='close',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='jsonmodel',
            name='high',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='jsonmodel',
            name='low',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='jsonmodel',
            name='open',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
